#ifndef DIVER_SWIMMING_SPRITE_H
#define DIVER_SWIMMING_SPRITE_H

#include <gb/gb.h>

#define DIVER_SWIMMING_SPRITE_WIDTH 16u
#define DIVER_SWIMMING_SPRITE_HEIGHT 8u
#define DIVER_SWIMMING_SPRITE_WIDTH_TILES 2u
#define DIVER_SWIMMING_SPRITE_HEIGHT_TILES 1u
#define DIVER_SWIMMING_SPRITE_FRAME_COUNT 1u
#define DIVER_SWIMMING_SPRITE_TILES_PER_FRAME (DIVER_SWIMMING_SPRITE_WIDTH_TILES * DIVER_SWIMMING_SPRITE_HEIGHT_TILES)
#define DIVER_SWIMMING_SPRITE_TILE_COUNT (DIVER_SWIMMING_SPRITE_FRAME_COUNT * DIVER_SWIMMING_SPRITE_TILES_PER_FRAME)

extern const unsigned char diver_swimming_sprite_tiles[];

void diver_swimming_sprite_show(UINT8 first_tile, UINT8 first_sprite, UINT8 frame, UINT8 x, UINT8 y);

#endif
