#ifndef HUD_PLACEHOLDER_TILES_H
#define HUD_PLACEHOLDER_TILES_H

#include <gb/gb.h>

#define HUD_PLACEHOLDER_TILE_BYTES 16u
#define HUD_PLACEHOLDER_TILE_COUNT 7u

#define HUD_PLACEHOLDER_BLANK_TILE_INDEX 0u
#define HUD_PLACEHOLDER_LINE_TILE_INDEX 1u
#define HUD_PLACEHOLDER_HEART_FULL_TILE_INDEX 2u
#define HUD_PLACEHOLDER_HEART_EMPTY_TILE_INDEX 3u
#define HUD_PLACEHOLDER_AIR_FULL_TILE_INDEX 4u
#define HUD_PLACEHOLDER_AIR_EMPTY_TILE_INDEX 5u
#define HUD_PLACEHOLDER_CAPTURE_EMPTY_TILE_INDEX 6u

extern const unsigned char hud_placeholder_tiles[];

#define HUD_PLACEHOLDER_AIR_PICKUP_TILE_DATA \
    (&hud_placeholder_tiles[HUD_PLACEHOLDER_AIR_FULL_TILE_INDEX * HUD_PLACEHOLDER_TILE_BYTES])

#endif
